import { useEffect, useMemo, useState } from 'react'

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'
const nav = [
  ['overview', 'Overview'], ['chunks', 'Chunks'], ['embeddings', 'Embeddings'],
  ['metadata', 'Metadata'], ['pipeline', 'Retrieval flow'], ['chat', 'Ask your documents'], ['remove', 'Remove document'], ['logout', 'Log out'],
]

const request = async (path, options = {}) => {
  const token = localStorage.getItem('rag_token')
  const headers = { ...(options.headers || {}) }
  if (token) headers.Authorization = `Bearer ${token}`
  const response = await fetch(`${API}${path}`, { ...options, headers })
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || 'Request failed')
  return response.json()
}

function Auth({ onDone }) {
  const resetToken = new URLSearchParams(window.location.search).get('reset_token')
  const [mode, setMode] = useState(resetToken ? 'reset' : 'login'), [form, setForm] = useState({ username: '', email: '', password: '', confirmPassword: '' }), [error, setError] = useState('')
  const setModeAndClear = nextMode => { setMode(nextMode); setError('') }
  const submit = async e => {
    e.preventDefault(); setError('')
    try {
      if (mode === 'signup') {
        await request('/auth/signup', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) })
        setError('Account created. Verify your email, then log in.'); setMode('login'); return
      }
      if (mode === 'forgot') {
        await request('/auth/forgot-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: form.email }) })
        setError('If an account exists for that email, a reset link has been sent.'); return
      }
      if (mode === 'reset') {
        if (form.password !== form.confirmPassword) throw new Error('Passwords do not match')
        await request('/auth/reset-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token: resetToken, new_password: form.password }) })
        window.history.replaceState({}, '', window.location.pathname)
        setError('Password reset successfully. You can now sign in.'); setMode('login'); return
      }
      const token = await request('/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: form.email, password: form.password }) })
      localStorage.setItem('rag_token', token.access_token); onDone()
    } catch (err) { setError(err.message) }
  }
  const heading = mode === 'login' ? 'Sign in to your workspace' : mode === 'signup' ? 'Create your workspace' : mode === 'forgot' ? 'Reset your password' : 'Choose a new password'
  const action = mode === 'login' ? 'Sign in' : mode === 'signup' ? 'Create account' : mode === 'forgot' ? 'Send reset link' : 'Reset password'
  return <main className="min-h-screen bg-slate-950 p-6 text-white grid place-items-center"><section className="grid w-full max-w-5xl overflow-hidden rounded-3xl bg-white text-slate-900 shadow-2xl md:grid-cols-2"><div className="hidden bg-gradient-to-br from-indigo-600 via-violet-600 to-cyan-500 p-12 text-white md:block"><p className="text-sm font-bold tracking-widest">RAG STUDIO</p><h1 className="mt-16 text-5xl font-semibold leading-tight">Make every document answerable.</h1><p className="mt-5 text-indigo-100">Upload, inspect chunks, trace retrieval, and chat with your knowledge base.</p></div><form onSubmit={submit} className="p-8 sm:p-12"><p className="text-sm font-semibold text-indigo-600">{mode === 'forgot' || mode === 'reset' ? 'ACCOUNT RECOVERY' : 'WELCOME BACK'}</p><h2 className="mt-2 text-3xl font-bold">{heading}</h2>{mode === 'signup' && <Input label="Username" value={form.username} onChange={v => setForm({ ...form, username: v })} />}{mode !== 'reset' && <Input label="Email" type="email" value={form.email} onChange={v => setForm({ ...form, email: v })} />}{mode !== 'forgot' && <Input label={mode === 'reset' ? 'New password' : 'Password'} type="password" value={form.password} onChange={v => setForm({ ...form, password: v })} />}{mode === 'reset' && <Input label="Confirm new password" type="password" value={form.confirmPassword} onChange={v => setForm({ ...form, confirmPassword: v })} />}{error && <p className="mt-4 text-sm text-rose-600">{error}</p>}<button className="mt-6 w-full rounded-xl bg-indigo-600 py-3 font-semibold text-white hover:bg-indigo-700">{action}</button>{mode === 'login' && <button type="button" onClick={() => setModeAndClear('forgot')} className="mt-4 w-full text-sm text-indigo-600 hover:text-indigo-700">Forgot password?</button>}{mode === 'login' && <button type="button" onClick={() => setModeAndClear('signup')} className="mt-4 w-full text-sm text-slate-500">New here? Create an account</button>}{mode === 'signup' && <button type="button" onClick={() => setModeAndClear('login')} className="mt-4 w-full text-sm text-slate-500">Already have an account? Sign in</button>}{(mode === 'forgot' || mode === 'reset') && <button type="button" onClick={() => { window.history.replaceState({}, '', window.location.pathname); setModeAndClear('login') }} className="mt-4 w-full text-sm text-slate-500">Back to sign in</button>}</form></section></main>
}
function Input({ label, type = 'text', value, onChange }) { return <label className="mt-5 block text-sm font-medium">{label}<input required type={type} value={value} onChange={e => onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-indigo-500" /></label> }

function Landing({ enter }) { return <main className="min-h-screen bg-slate-950 text-white"><nav className="mx-auto flex max-w-6xl items-center justify-between p-6"><b>◈ RAG STUDIO</b><button onClick={enter} className="rounded-lg border border-slate-600 px-4 py-2 text-sm">Sign in</button></nav><section className="mx-auto max-w-5xl px-6 py-24 text-center"><p className="inline rounded-full border border-indigo-400/40 bg-indigo-400/10 px-4 py-2 text-sm text-indigo-200">Document intelligence, made transparent</p><h1 className="mt-8 text-5xl font-bold tracking-tight sm:text-7xl">See how your AI<br/><span className="text-indigo-400">finds the answer.</span></h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-slate-300">A focused RAG workspace for ingesting documents, auditing chunks and embeddings, and asking context-aware questions.</p><button onClick={enter} className="mt-10 rounded-xl bg-indigo-500 px-6 py-3 font-semibold hover:bg-indigo-400">Open workspace →</button></section></main> }

function Dashboard({ onLogout }) {
  const [page, setPage] = useState('overview'), [documents, setDocuments] = useState([]), [selected, setSelected] = useState(null), [detail, setDetail] = useState([]), [chats, setChats] = useState([]), [chatId, setChatId] = useState(null), [messages, setMessages] = useState([]), [question, setQuestion] = useState(''), [notice, setNotice] = useState(''), [retrievalTrace, setRetrievalTrace] = useState(null)
  const loadDocs = async () => { try { const result = await request('/documents'); setDocuments(result); if (!selected && result[0]) setSelected(result[0]) } catch (e) { setNotice(e.message) } }
  const loadChats = async () => { try { setChats(await request('/chats')) } catch {} }
  useEffect(() => { loadDocs(); loadChats() }, [])
  useEffect(() => { if (!selected) return; const endpoint = page === 'chunks' ? 'chunks' : page === 'embeddings' ? 'embeddings' : page === 'metadata' ? 'metadata' : null; if (endpoint) request(`/documents/${selected.id}/${endpoint}`).then(x => setDetail(Array.isArray(x) ? x : [x])).catch(e => setNotice(e.message)) }, [page, selected])
  const upload = async e => { const file = e.target.files?.[0]; if (!file) return; const data = new FormData(); data.append('file', file); try { setNotice('Uploading and creating embeddings…'); await request('/upload', { method: 'POST', body: data }); await loadDocs(); setNotice('Document processed successfully.') } catch (err) { setNotice(err.message) } }
  const createChat = async () => { try { const c = await request('/chat/new', { method: 'POST' }); setChatId(c.chat_id); setMessages([]); await loadChats(); setPage('chat') } catch (e) { setNotice(e.message) } }
  const openChat = async id => { setChatId(id); setPage('chat'); try { setMessages(await request(`/chat/${id}/history`)) } catch (e) { setNotice(e.message) } }
  const clearChat = async id => { try { await request(`/chat/${id}`, { method: 'DELETE' }); if (chatId === id) { setChatId(null); setMessages([]); setRetrievalTrace(null) }; await loadChats() } catch (e) { setNotice(e.message) } }
  const clearAllChats = async () => { try { await request('/chats', { method: 'DELETE' }); setChatId(null); setMessages([]); setRetrievalTrace(null); await loadChats(); setNotice('Chat history deleted.') } catch (e) { setNotice(e.message) } }
  const logout = async () => {
    try {
      await request('/auth/logout', { method: 'POST' })
    } catch (error) {
      // Clear the local session even if the token has already expired or the API is unavailable.
      console.error('Logout error:', error)
    } finally {
      localStorage.removeItem('rag_token')
      onLogout()
    }
  }
  useEffect(() => { if (page === 'logout') logout() }, [page])
  const ask = async e => { e.preventDefault(); if (!question.trim()) return; if (!selected) { setNotice('Upload and select a document before asking a question.'); return } let id = chatId; if (!id) { const c = await request('/chat/new', { method: 'POST' }); id = c.chat_id; setChatId(id); await loadChats() } const text = question; setQuestion(''); setRetrievalTrace(null); setMessages(m => [...m, { role: 'user', content: text }, { role: 'assistant', content: '' }]); try { const trace = await request('/retrieval/inspect', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question: text, document_id: selected.id }) }); setRetrievalTrace(trace); const token = localStorage.getItem('rag_token'); const r = await fetch(`${API}/chat`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ chat_id: id, message: text, document_id: selected.id }) }); if (!r.ok) throw new Error((await r.json().catch(() => ({}))).detail || 'Chat request failed'); const reader = r.body.getReader(), decoder = new TextDecoder(); let answer = ''; while (true) { const { done, value } = await reader.read(); if (done) break; answer += decoder.decode(value); setMessages(m => [...m.slice(0, -1), { role: 'assistant', content: answer }]) } } catch (err) { setNotice(err.message); setMessages(m => m.slice(0, -1)) } }
  const title = nav.find(n => n[0] === page)?.[1]
  return <div className="min-h-screen bg-slate-50 text-slate-900 lg:flex"><aside className="w-full bg-slate-950 p-5 text-slate-300 lg:min-h-screen lg:w-72"><b className="text-white">◈ RAG STUDIO</b><label className="mt-8 block cursor-pointer rounded-xl border border-dashed border-slate-600 p-4 text-sm hover:border-indigo-400"><input className="hidden" type="file" onChange={upload}/><span className="block font-semibold text-white">＋ Upload file</span><span className="mt-1 block text-xs">PDF, DOCX, TXT and more</span></label><div className="mt-7 space-y-1">{nav.map(([id, text]) => <button key={id} onClick={() => setPage(id)} className={`w-full rounded-lg px-3 py-2 text-left text-sm ${page === id ? 'bg-indigo-500 text-white' : 'hover:bg-slate-800'}`}>{text}</button>)}</div><div className="mt-8 border-t border-slate-800 pt-5"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-wider text-slate-500">Chat history <button onClick={createChat}>＋</button></div>{chats.map(c => <button key={c.chat_id} onClick={() => openChat(c.chat_id)} className="mt-2 block w-full truncate rounded px-2 py-1 text-left text-sm hover:bg-slate-800">Chat #{c.chat_id}</button>)}</div></aside><main className="min-w-0 flex-1 p-5 sm:p-9"><header className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-slate-500">Knowledge workspace</p><h1 className="text-3xl font-bold">{title}</h1></div>{documents.length > 0 && <select value={selected?.id} onChange={e => setSelected(documents.find(d => d.id === +e.target.value))} className="rounded-lg border bg-white p-2 text-sm">{documents.map(d => <option key={d.id} value={d.id}>{d.title}</option>)}</select>}</header>{notice && <p className="mb-5 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">{notice}</p>}<Page page={page} docs={documents} doc={selected} detail={detail} messages={messages} question={question} setQuestion={setQuestion} ask={ask} /></main></div>
}


function Page({ page, docs, doc, detail, messages, question, setQuestion, ask }) {
  if (page === 'remove') return <RemoveDocument docs={docs} selectedDocument={doc} />
  if (page === 'overview') return <div><div className="grid gap-4 sm:grid-cols-3"><Metric label="Documents" value={docs.length}/><Metric label="Total chunks" value={docs.reduce((n, d) => n + d.chunk_count, 0)}/><Metric label="Selected document" value={doc?.chunk_count || '—'} suffix=" chunks"/></div><section className="mt-8 rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Your documents</h2>{docs.length ? docs.map(d => <div key={d.id} className="mt-4 flex justify-between rounded-xl bg-slate-50 p-4 text-sm"><span>{d.title}</span><span>{d.chunk_count} chunks</span></div>) : <p className="mt-3 text-sm text-slate-500">Upload a document to start the ingestion pipeline.</p>}</section></div>
  if (page === 'pipeline') return <Pipeline documentId={doc?.id} />
  if (page === 'chat') return <ChatPanel doc={doc} messages={messages} question={question} setQuestion={setQuestion} ask={ask} />
  if (page === 'chat') return <section className="flex min-h-[65vh] flex-col rounded-2xl bg-white shadow-sm"><div className="border-b p-5"><b>Document agent</b><p className="text-sm text-slate-500">Answers are grounded in relevant uploaded chunks when available.</p></div><div className="flex-1 space-y-4 p-5">{messages.length ? messages.map((m, i) => <div key={i} className={`max-w-3xl rounded-2xl p-4 text-sm leading-6 ${m.role === 'user' ? 'ml-auto bg-indigo-600 text-white' : 'bg-slate-100'}`}>{m.content || 'Thinking…'}</div>) : <p className="text-sm text-slate-500">Start a conversation about your documents.</p>}</div><form onSubmit={ask} className="flex gap-3 border-t p-4"><input value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask a question about your documents…" className="min-w-0 flex-1 rounded-xl border p-3 outline-none focus:border-indigo-500"/><button className="rounded-xl bg-indigo-600 px-5 font-semibold text-white">Send</button></form></section>
  const heading = page === 'chunks' ? 'First 10 chunks' : page === 'embeddings' ? 'Embedding preview — first 5 chunks' : 'Document metadata and summary'
  return <section><p className="mb-5 text-sm text-slate-500">{heading}</p>{doc ? <div className="space-y-4">{detail.map((item, i) => <article key={item.id || i} className="rounded-2xl bg-white p-5 shadow-sm"><div className="mb-3 flex justify-between"><b>{page === 'metadata' ? item.title : `Chunk ${item.chunk_index}`}</b>{item.embedding_dimensions && <span className="text-xs text-indigo-600">{item.embedding_dimensions} dimensions</span>}</div>{page === 'metadata' ? <><p className="text-sm text-slate-500">Source: {item.source || 'Unknown'} · {item.created_at ? new Date(item.created_at).toLocaleString() : ''}</p><ul className="mt-4 list-disc space-y-2 pl-5 text-sm">{item.key_points?.map((x, j) => <li key={j}>{x}</li>)}</ul></> : <><p className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{item.content}</p>{item.embedding_preview && <code className="mt-4 block overflow-auto rounded bg-slate-950 p-3 text-xs text-emerald-300">[{item.embedding_preview.map(n => n.toFixed(4)).join(', ')}, …]</code>}</>}</article>)}</div> : <p className="rounded-xl bg-white p-6 text-slate-500">Upload and select a document first.</p>}</section>
}
function Metric({ label, value, suffix = '' }) { return <div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}{suffix}</p></div> }
function RemoveDocument({ docs, selectedDocument }) {
  const [documentId, setDocumentId] = useState(selectedDocument?.id || '')
  const [error, setError] = useState('')
  const remove = async () => {
    const document = docs.find(item => item.id === Number(documentId))
    if (!document) return
    if (!window.confirm(`Delete “${document.title}” and all of its chunks? This cannot be undone.`)) return
    try {
      await request(`/documents/${document.id}`, { method: 'DELETE' })
      window.location.reload()
    } catch (err) {
      setError(err.message)
    }
  }
  if (!docs.length) return <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Remove document</h2><p className="mt-3 text-sm text-slate-500">There are no documents to remove.</p></section>
  return <section className="max-w-xl rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Remove document</h2><p className="mt-2 text-sm text-slate-500">Deleting a document permanently removes its chunks and embeddings from the database.</p><label className="mt-5 block text-sm font-medium">Document<select value={documentId} onChange={event => setDocumentId(event.target.value)} className="mt-2 w-full rounded-lg border bg-white p-3">{docs.map(document => <option key={document.id} value={document.id}>{document.title}</option>)}</select></label>{error && <p className="mt-3 text-sm text-rose-600">{error}</p>}<button onClick={remove} className="mt-5 rounded-lg bg-rose-600 px-4 py-3 text-sm font-semibold text-white hover:bg-rose-700">Delete document</button></section>
}
function ChatPanel({ doc, messages, question, setQuestion, ask }) {
  const clearHistory = async () => {
    if (!window.confirm('Delete every saved chat?')) return
    try { await request('/chats', { method: 'DELETE' }); window.location.reload() } catch (error) { window.alert(error.message) }
  }
  return <section className="flex min-h-[65vh] flex-col rounded-2xl bg-white shadow-sm"><div className="flex items-start justify-between border-b p-5"><div><b>Document agent</b><p className="text-sm text-slate-500">Answering only from: {doc?.title || 'select a document first'}.</p></div><button onClick={clearHistory} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-700">Clear chat history</button></div><div className="flex-1 space-y-4 p-5">{messages.length ? messages.map((m, i) => <div key={i} className={`max-w-3xl whitespace-pre-wrap rounded-2xl p-4 text-sm leading-6 ${m.role === 'user' ? 'ml-auto bg-indigo-600 text-white' : 'bg-slate-100'}`}>{m.content || 'Thinking...'}</div>) : <p className="text-sm text-slate-500">Use Retrieval flow to inspect each chunk selected as evidence.</p>}</div><form onSubmit={ask} className="flex gap-3 border-t p-4"><input value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask the selected document..." className="min-w-0 flex-1 rounded-xl border p-3 outline-none focus:border-indigo-500"/><button className="rounded-xl bg-indigo-600 px-5 font-semibold text-white">Send</button></form></section>
}
function Pipeline({ documentId }) {
  const steps = [
    ['Query rewriting', 'Makes a follow-up question self-contained using prior messages, so retrieval understands words such as “it” or “that”.'],
    ['Vector search', 'Embeds the question and returns the ten closest chunks owned by the signed-in user.'],
    ['Reranker', 'A CrossEncoder reads the question together with each candidate chunk, then orders the five most relevant chunks. If that model is unavailable, the app safely retains vector-search order and clearly reports it.'],
    ['Relevance check', 'Checks the strongest score before giving any text to the model. This prevents an unrelated document from being used as evidence.'],
    ['Context writing', 'Joins the approved chunk text with separators. That is the exact evidence supplied to the answering model.'],
    ['Answer + memory', 'The answer is streamed to chat and both messages are saved for later follow-up questions.'],
  ]
  const [selectedStep, setSelectedStep] = useState(2), [query, setQuery] = useState(''), [trace, setTrace] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(false), [chats, setChats] = useState([]), [chatId, setChatId] = useState('')
  useEffect(() => { request('/chats').then(setChats).catch(() => {}) }, [])
  const inspect = async e => { e.preventDefault(); if (!query.trim()) return; if (!documentId) { setError('Select a document before running retrieval.'); return } setLoading(true); setError(''); try { setTrace(await request('/retrieval/inspect', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question: query, document_id: documentId, ...(chatId ? { chat_id: Number(chatId) } : {}) }) })) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  const active = steps[selectedStep]
  return <PipelineInspector steps={steps} selectedStep={selectedStep} setSelectedStep={setSelectedStep} active={active} query={query} setQuery={setQuery} inspect={inspect} documentId={documentId} loading={loading} error={error} trace={trace} chats={chats} chatId={chatId} setChatId={setChatId} />
  return <div className="space-y-6"><section className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm text-slate-500">Click a stage to understand what it does. Use the checker to run the same retrieval path as chat before asking.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{steps.map(([title], i) => <button key={title} onClick={() => setSelectedStep(i)} className={`rounded-xl border p-4 text-left ${selectedStep === i ? 'border-indigo-500 bg-indigo-50' : 'border-slate-200 hover:border-indigo-300'}`}><span className="text-xs font-bold text-indigo-600">STEP {i + 1}</span><b className="mt-1 block">{title}</b></button>)}</div><article className="mt-5 rounded-xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold text-indigo-300">{active[0].toUpperCase()}</p><p className="mt-2 text-sm leading-6 text-slate-200">{active[1]}</p></article></section><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Check your document retrieval</h2><form onSubmit={inspect} className="mt-4 flex gap-3"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Type a question about an uploaded document" className="min-w-0 flex-1 rounded-xl border p-3 outline-none focus:border-indigo-500"/><button disabled={loading} className="rounded-xl bg-indigo-600 px-5 text-sm font-semibold text-white disabled:opacity-60">{loading ? 'Checking…' : 'Run check'}</button></form>{error && <p className="mt-3 text-sm text-rose-600">{error}</p>}{trace && <div className="mt-5 space-y-4 text-sm"><p className={`rounded-lg p-3 ${trace.relevant ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'}`}>{trace.reason}</p>{trace.reranker_warning && <p className="rounded-lg bg-amber-50 p-3 text-amber-800">{trace.reranker_warning}</p>}<TraceList title="Vector search candidates" rows={trace.vector_candidates} scoreLabel="similarity"/><TraceList title={trace.used_reranker ? 'Reranked chunks' : 'Selected chunks (vector fallback)'} rows={trace.reranked_chunks} scoreLabel="score"/></div>}</section></div>
}
function PipelineInspector({ steps, selectedStep, setSelectedStep, active, query, setQuery, inspect, documentId, loading, error, trace, chats, chatId, setChatId }) {
  return <div className="space-y-6"><section className="rounded-2xl bg-white p-6 shadow-sm"><p className="text-sm text-slate-500">Run the same retrieval stages used by chat and inspect the inputs and resulting context.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{steps.map(([title], index) => <button key={title} onClick={() => setSelectedStep(index)} className={`rounded-xl border p-4 text-left ${selectedStep === index ? 'border-indigo-500 bg-indigo-50' : 'border-slate-200 hover:border-indigo-300'}`}><span className="text-xs font-bold text-indigo-600">STEP {index + 1}</span><b className="mt-1 block">{title}</b></button>)}</div><article className="mt-5 rounded-xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold text-indigo-300">{active[0].toUpperCase()}</p><p className="mt-2 text-sm leading-6 text-slate-200">{active[1]}</p></article></section><section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="font-bold">Check your document retrieval</h2><form onSubmit={inspect} className="mt-4 space-y-3"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Type a question about an uploaded document" className="w-full rounded-xl border p-3 outline-none focus:border-indigo-500"/><label className="block text-sm text-slate-600">Chat history for query rewriting (optional)<select value={chatId} onChange={event => setChatId(event.target.value)} className="mt-1 block w-full rounded-lg border bg-white p-3"><option value="">No prior chat — query stays standalone</option>{chats.map(chat => <option key={chat.chat_id} value={chat.chat_id}>Chat #{chat.chat_id}</option>)}</select></label><button disabled={loading || !documentId} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{loading ? 'Checking…' : 'Run check'}</button></form>{error && <p className="mt-3 text-sm text-rose-600">{error}</p>}{trace && <div className="mt-5 space-y-4 text-sm"><p className={`rounded-lg p-3 ${trace.relevant ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'}`}>{trace.reason}</p><TraceOutput label="Original query" value={trace.original_query}/><TraceOutput label="Rewritten query used for retrieval" value={trace.rewritten_query}/><TraceOutput label={`Final context sent to the model (${trace.context_chunk_count || 0} chunks)`} value={trace.context_text} empty="No context was sent because no chunk passed the relevance check."/>{trace.reranker_warning && <p className="rounded-lg bg-amber-50 p-3 text-amber-800">{trace.reranker_warning}</p>}<TraceList title="Vector search candidates" rows={trace.vector_candidates} scoreLabel="similarity"/><TraceList title={trace.used_reranker ? 'Reranked chunks' : 'Selected chunks (vector fallback)'} rows={trace.reranked_chunks} scoreLabel="score"/></div>}</section></div>
}
function TraceOutput({ label, value, empty = 'No value was returned.' }) { return <details className="rounded-xl border border-slate-200 bg-slate-50 p-4" open><summary className="cursor-pointer font-semibold text-slate-800">{label}</summary><pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap font-sans text-xs leading-5 text-slate-700">{value || empty}</pre></details> }
function TraceList({ title, rows = [], scoreLabel }) { return <div><b>{title}</b>{rows.length ? <div className="mt-2 space-y-2">{rows.map(row => <details key={row.chunk_id} className="rounded-lg bg-slate-50 p-3"><summary className="cursor-pointer"><span className="font-semibold">Chunk {row.chunk_index + 1}</span><span className="ml-2 text-xs text-indigo-600">{scoreLabel}: {row[scoreLabel]}</span></summary><p className="mt-2 text-xs font-medium text-slate-500">{row.document_title} (document #{row.document_id})</p><p className="mt-2 whitespace-pre-wrap text-xs leading-5 text-slate-600">{row.content || row.preview}</p></details>)}</div> : <p className="mt-2 text-slate-500">No chunks were returned.</p>}</div> }
export default function App() { const [screen, setScreen] = useState(localStorage.getItem('rag_token') ? 'app' : 'landing'); return screen === 'landing' ? <Landing enter={() => setScreen('auth')}/> : screen === 'auth' ? <Auth onDone={() => setScreen('app')}/> : <Dashboard onLogout={() => setScreen('auth')}/> }
